server:
  domain: http://nf585696.natappfree.cc/
  port: 8080
  tomcat:
    max-http-form-post-size: 20MB   # 解析 multipart 的总大小上限
    max-swallow-size: 20MB          # 上传被中断时可吞掉的最大数据，-1 表示不限制

redis:
  sdk:
    config:
      host: 117.72.90.80
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      password: Haitao2003@

ai:
  api-key:
    chat-glm: 78d76d30bd1948899167a0bd85bab9bd.IhrSn6lWqAF6ahyO
    doubao: dd05458e-919e-435d-873e-ccc122a63375


spring:
  servlet:
    multipart:
      max-file-size: 20MB # 上传单个文件的最大大小
      max-request-size: 20MB # 上传多个文件时，所有文件的总大小上限
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,file:D:/Java_project/ImageAI/uploads/
