server:
  port: 8080

redis:
  sdk:
    config:
      host: 117.72.90.80
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      password: Haitao2003@

ai:
  api-key:
    chat-glm: 78d76d30bd1948899167a0bd85bab9bd.IhrSn6lWqAF6ahyO